//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Emp_Adm_Profile.Models
{
    using System;
    using System.Collections.Generic;

    public partial class NewsFeed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewsFeed()
        {
            this.Emps = new HashSet<Emp>();
        }

        public int NId { get; set; }
        public Nullable<int> AId { get; set; }
        public string Topic { get; set; }
        public string Descrip { get; set; }
        public System.DateTime NDate { get; set; }

        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp> Emps { get; set; }
    }
}
