//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Emp_Adm_Profile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queryfeed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Queryfeed()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int QId { get; set; }
        public string Query { get; set; }
        public string Category { get; set; }
        public System.DateTime QDate { get; set; }
        public Nullable<int> EId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Emp Emp { get; set; }
    }
}
